/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_myapplication2_OpenCvModule */

#ifndef _Included_com_example_myapplication2_OpenCvModule
#define _Included_com_example_myapplication2_OpenCvModule
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_myapplication2_OpenCvModule
 * Method:    ConvertRGBtoGray
 * Signature: (JJ)[I
 */
JNIEXPORT jintArray JNICALL Java_com_example_myapplication2_OpenCvModule_ConvertRGBtoGray
  (JNIEnv *, jobject, jlong, jlong);

#ifdef __cplusplus
}
#endif
#endif
